version: '3.8'

networks:
  rabbitmq:
    driver: bridge

services:
  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: docker.io/rabbitmq:management
    volumes:
      - ./data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:15672/"]
      interval: 30s
      timeout: 10s
      retries: 3

